---
  - name: Update the software package repository
    command: yum update -y

  # nginx
  - name: Install nginx
    command: amazon-linux-extras install nginx1 -y

  - name: Setup nginx
    block:
      - name: Create blog.conf file
        copy:
          src: nginx/blog.conf
          dest: /etc/nginx/conf.d/blog.conf

      - name: Configure nginx to auto-start
        command: chkconfig nginx on || systemctl enable nginx.service

      - name: Update nginx.conf file
        copy:
          src: nginx/nginx.conf
          dest: /etc/nginx/nginx.conf

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
